### ISSUE TITLE
v0.19.0 standalone packages have wrong permission

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-cli#256]
Unpacked standlone binary for macOS and Linux will not work correctly due to wrong permissions.

```
$ ls -l
total 445808
--wxrw--wt  1 yhatt  staff  112802551  7 19 02:16 marp
-rwxr-xr-x@ 1 yhatt  staff  115445966  7 10 00:44 marp-v0.18.3
```

```
$ ./marp
internal/fs/utils.js:230
    throw err;
    ^

Error: EACCES: permission denied, open '/Users/yhatt/Downloads/marp'
    at Object.openSync (fs.js:458:3)
    at internal/bootstrap/pkg.js:35:17
    at internal/bootstrap/pkg.js:43:4
    at internal/bootstrap/pkg.js:44:2 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/Users/yhatt/Downloads/marp'
}
```

Require running `chmod 755 ./marp` to work Marp CLI v0.19.0. I'm going to replace assets for v0.19.0 that have wrong permission.

**Comment by yhatt** [comment]
Updated v0.19.0 assets for macOS and Linux to new package, and confirmed they are working now. I'm going to fix an essential issue.
