### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by DorKeinath** [marp-team/marp-cli#449]
With both: marp and npx I get 
> SyntaxError: Unexpected token ;

In my markdown-file there is no ";"
What can I try?

More details with marp:

/usr/local/lib/node_modules/@marp-team/marp-cli/lib/marp-cli-deae881a.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";var e=require("process"),t=require("os"),r=require("tty"),n=require("yargs/yargs"),o=require("yargs"),s=require("fs"),i=require("path"),a=require("cosmiconfig"),u=require("util"),c=require("child_process"),l=require("url"),p=require("import-from"),A=require("stream"),D=require("events"),f=require("tmp"),d=require("@marp-team/marpit"),h=require("puppeteer-core"),g=require("net"),m=require("is-wsl"),v=require("crypto"),b=require("chokidar"),y=require("ws"),C=require("querystring"),w=require("serve-index"),E=require("@marp-team/marp-core/package.json");function F(e){return e&&"object"==typeof e&&"default"in e?e:{default:e}}function B(e){if(e&&e.__esModule)return e;var t=Object.create(null);return e&&Object.keys(e).forEach((function(r){if("default"!==r){var n=Object.getOwnPropertyDescriptor(e,r);Object.defineProperty(t,r,n.get?n:{enumerable:!0,get:function(){retur

SyntaxError: Unexpected token ;
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/usr/local/lib/node_modules/@marp-team/marp-cli/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/usr/local/lib/node_modules/@marp-team/marp-cli/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/usr/local/lib/node_modules/@marp-team/marp-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/@marp-team/marp-cli/lib/marp-cli.js:1:137)

**Comment by yhatt** [comment]
You may still have a cache for the outdated version of Marp CLI, generated by an upstream library [`v8-compile-cache`](https://github.com/zertosh/v8-compile-cache).

Try `DISABLE_V8_COMPILE_CACHE=1 npx @marp-team/marp-cli@latest ./your-markdown.md`. If worked, you should consider to clean up caches in `<os.tmpdir()>/v8-compile-cache-*`.
https://github.com/zertosh/v8-compile-cache#options

**Comment by yhatt** [comment]
As a premise, which version of Node.js are you using? Marp CLI only supports active Node.js. (https://nodejs.org/about/releases/)

**Comment by yhatt** [comment]
We've confirmed that this error reproduces when trying to use Marp CLI with outdated Node.js 10. We have only supported [the active LTS Node.js](https://nodejs.org/about/releases/) (Node.js >= 14 in v2.0.0). Try to upgrade your Node.js to the latest LTS.
