### ISSUE TITLE
Marp CLI 3.0.0 standalone binary is missing setup-sandbox.js

### ISSUE THREAD

**Issue by silkeh** [marp-team/marp-cli#524]
### Version of Marp Tool

3.0.0

### Operating System

Linux

### Environment

- OS version: Debian 11, Solus
- Node.js version (Marpit / Marp Core/ Marp CLI): v18.5.0 (bundled with release)
- VS Code version (Marp for VS Code): n/a

### How to reproduce

1. Download binary from releases page or build from source
2. Run `./marp --version` (or any other marp command)

### Expected behavior

Shows the version, eg:

```
$ marp --version
@marp-team/marp-cli v2.5.0 (w/ @marp-team/marp-core v3.6.0)
```

### Actual behavior

```
$ marp --version
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: File '/**/marp-cli/node_modules/vm2/lib/setup-sandbox.js' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1046:29)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1094:18)
    at Object.<anonymous> (/snapshot/marp-cli/node_modules/vm2/lib/vm.js:148:57)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31) {
  errno: -2,
  code: 'ENOENT',
  path: '/snapshot/marp-cli/node_modules/vm2/lib/setup-sandbox.js',
  pkg: true
}

Node.js v18.5.0
```

**Comment by yhatt** [comment]
Related: https://github.com/vercel/pkg/issues/1812

**Comment by jans-code** [comment]
This is not only an error with the linux binary.
I have this with the linux binary under Archlinux (same error as silkeh) and but also with the windows binary.

```
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: File 'C:\**\marp-cli\node_modules\vm2\lib\setup-sandbox.js' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:657:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1046:29)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1094:18)
    at Object.<anonymous> (C:\snapshot\marp-cli\node_modules\vm2\lib\vm.js:148:57)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31) {
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\snapshot\\marp-cli\\node_modules\\vm2\\lib/setup-sandbox.js',
  pkg: true
}

Node.js v18.5.0
```

**Comment by yhatt** [comment]
Probably a packaged binary by pkg is not yet available dynamic import for ESM.
https://github.com/vercel/pkg/issues/1291

We must adopt the traditional way `require()` if Marp CLI is run via the standalone binary (Detectable with `process.pkg`). In this case, the engine cannot be ESM.
