### ISSUE TITLE
Marp crashes with NodeJS LTS 18.18.0

### ISSUE THREAD

**Issue by chrisdecker1201** [marp-team/marp-cli#546]
### Version of Marp Tool

Marp CLI v3.2.1

### Operating System

Windows

### Environment

- OS version: Windows 10
- Node.js version: 18.18.0 (LTS)
- Marp CLI: v3.2.1

### How to reproduce

1. Install NodeJS 18.18.0 on Windows via choco

```bash
choco install nodejs-lts --version=18.18.0
```

2. Install Marp CLI

```bash
npm install -g @marp-team/marp-cli
```

3. Execute marp in server mode

```bash
marp -s -I .
```

### Expected behavior

Same behaviour like in version 18.17.0.

I downgraded now and it's working :)

### Actual behavior

The marp-cli command just return this error.

```log
node:internal/fs/promises:590
    await binding.openFileHandle(pathModule.toNamespacedPath(path),
                  ^

Error: ENOENT: no such file or directory, open
    at open (node:internal/fs/promises:590:19)
    at Object.readFile (node:internal/fs/promises:1025:20)
    at Bc.load (C:\Users\tb10dcc\AppData\Roaming\npm\node_modules\@marp-team\marp-cli\lib\marp-cli-376cca40.js:27:75570)
    at o (C:\Users\tb10dcc\AppData\Roaming\npm\node_modules\@marp-team\marp-cli\lib\marp-cli-376cca40.js:43:90184)
    at Lp.convertFile (C:\Users\tb10dcc\AppData\Roaming\npm\node_modules\@marp-team\marp-cli\lib\marp-cli-376cca40.js:43:91002)
    at Lp.convertFiles (C:\Users\tb10dcc\AppData\Roaming\npm\node_modules\@marp-team\marp-cli\lib\marp-cli-376cca40.js:43:91214)
    at async Vp (C:\Users\tb10dcc\AppData\Roaming\npm\node_modules\@marp-team\marp-cli\lib\marp-cli-376cca40.js:43:126747) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open'
}

Node.js v18.18.0
```

### Additional information

I use this here for just saying thank you for this great tool ❤.

**Comment by yhatt** [comment]
I've tested with Node.js 18.18.0 installed via [the msi installer](https://nodejs.org/en/download), but I could not reproduce the error on my Windows. If the error was brought by the specific directory structure, please share the structure for reproduction.

The stack trace shows it has brought the error by the Node.js internal module so Node.js installed via Chocolately might be causing something wrong (I could not test because I'm not a Chocolately user). It's hard to imagine there are some internal differences in the Node.js binary between installed via msi and via Chocolately, but I recommend reporting it to the Node.js issue tracker just in case.

**Comment by chrisdecker1201** [comment]
I just uninstalled nodejs-lts with choco

````bash
choco uninstall nodejs-lts
```

And installed NodeJS 18.18.0 from the MSI (https://nodejs.org/en/download), but I'm still getting this error... 
I will open a bug on Node.js

**Comment by yhatt** [comment]
Caused by upstream: https://github.com/nodejs/node/issues/48673
